### ISSUE TITLE
get_playlist_audio_features - Returns Error

### ISSUE THREAD

**Issue by gndaniela** [charlie86/spotifyr#114]
Hi!
I've been using the package without any problems, but today, re-running some code, I'm getting this error:

get_playlist_audio_features('spotify',"37i9dQZF1DX4UtSsGT1Sbe")
`Error: object 'track.id' not found`

I've seen this was an isssue in the past and was fixed, but maybe it's bugged again? 
All updates are installed and library(spotifyr) was called as well.

Thanks! :)

**Comment by antaldaniel** [comment]
I have a patch for this, and many similar issues, but I think that it would require a through overview of the code.  As spotifyR is a bit behind dependencies and a few pull requests, I'd gladly send these patches in a coordinated way [ and of course, I can provide you with my version of the function, but it would be better to include it in a major new release.]

The problem is that that Spotify API sends back data where variable names are not always the same. Some of these exceptions are handled, such as album.release vs album_release, but not track.id and track_id.  This funciton has three naming issues, and three further exception handling must be added: whenever you have track.id, for example, it has to be renamed to track_id.

**Comment by gndaniela** [comment]
Thanks for the answer! Now I get why it threw the error. :)
Fortunately, at some point it started to work again, (or I found a workaround calling other functions, I really don't remember).
Let's hope the code improves with those patches some day!

Thanks again!
