### ISSUE TITLE
package archived in CRAN

### ISSUE THREAD

**Issue by harshvardhaniimi** [charlie86/spotifyr#119]
The package isn't available on CRAN anymore because of some outdated packages. Please check if something could be done about it.
Also, please add a list of all functions - something like documentation. That'd really help. Great work by the way!

**Comment by andodet** [comment]
Not the mantainer here. You can find documentation [here][1] or by `??spotifyr` in your R console.

[1]: https://www.rcharlie.com/spotifyr/

**Comment by harshvardhaniimi** [comment]
There are more functions than what are mentioned on the blog you mentioned. Also `??spotifyr` doesn't work.

**Comment by harshvardhaniimi** [comment]
Sorry for the late reply: I downloaded the source codes of the package and thankfully they were detailed enough. That worked for me.

**Comment by niessen** [comment]
The problem which led to archiving has been resolved ( #112), so this issue could probably be fixed by resubmitting to CRAN.

**Comment by andodet** [comment]
@charlie86 Looping you in this one as I believe that resubmitting `spotifyr` to CRAN would benefit many users and avoid workarounds for applications depending on it.

**Comment by r-leyshon** [comment]
As on the [CRAN website](https://cran.r-project.org/web/packages/spotifyr/index.html)

"Archived on 2020-05-03 as requires archived package 'genius'."

Keen to know if this will be remedied any time soon.

**Comment by antaldaniel** [comment]
@JosiahParry , is a hard dependency necessary, cannot [genius](https://github.com/josiahparry/genius)  only be suggested?

**Comment by JosiahParry** [comment]
@antaldaniel It can be suggested. No hard requirement. Was it taken off of CRAN?

**Comment by antaldaniel** [comment]
@JosiahParry Yes, it was. It's been a long time since the last release, and I think that the most labourous issue is broken links in the documentation.  But also, if a dependency is taken down from CRAN, it pulls down all downstream packages, and therefore only actively maintained packages should remain hard dependencies.  (I think it was not genius that pulled down spotifyr, but ggjoy in the README, which is superseded by ggridges; but anyway, you either maintain actively genius, or it shoudl be suggested.)

I am not sure how much effort it will take to get the package back to CRAN, by the way. The biggest challenge is that they do not accept \dontrun{} anymore, only \donttest{}, and all the examples require Spotify Web API authorization.  But I am looking into how other API wrapper packages solve this.

**Comment by JosiahParry** [comment]
Yes, that issue was resolved nearly a year ago. 

I presently maintain genius. I too am going through the challenges associated with changes to CRAN. 

All examples in `spotifyr` should be wrapped in `donttest{}`. This will ensure that CRAN checks do not try and test the functions and error with non-zero exit.

**Comment by antaldaniel** [comment]
@JosiahParry  Thanks, I was just working on updating the genius functions.  They are heavily affected by changes in tibble, and the `.Rbuildignore` is updated.   I'd like to get in touch with you about genius. I'll send you message or leave a note there.

**Comment by JosiahParry** [comment]
@antaldaniel please do open an issue if you find any issues. There are none related to tibble presently that I am aware of.
