### ISSUE TITLE
Possible bug/limitation with get_my_recently_played() when using before/after options

### ISSUE THREAD

**Issue by lucasjl** [charlie86/spotifyr#175]
Hello and happy 2022 :) If you're reading this in the future, I hope your 2022 went well.

I'm new to R and I created a personal project to plot some charts to understand how my audio features (danceability, valence, etc) change depending on the time of the day I listen to music. To do that I wanted to collect at least some weeks of recently played songs using get_my_recently_played().

I know the get_my_recently_played() limit is 50, however my idea was to create iterations using the 'before' parameter to keep getting 50 songs after 50 songs each time I called this function. However, I don't get any results when running this function with the 'before' parameter. In addition, any 'after' parameters I put don't seem to have any effect and keep showing the same last 20 songs I listened to regardless of which unix timestamp I put.

This is an example of code I tried to run using Unix = 1641235591 = Mon Jan 03 2022 18:46:31 GMT+0000

```
test_history <-get_my_recently_played(after = 1641235591)

test_history2 <-get_my_recently_played(before = 1641235591)
```

Is this a limitation or bug? Or am I just using it incorrectly? I can use other parameters such as limit, for example, but before/after don't seem to really work. 

If you do know any other ways to get more than the 50 last songs I heard and the time they were played, that would also work. Thank you so much!

**Comment by antaldaniel** [comment]
@lucasjl Best wishes to you as well from the present :)

The function makes call to the Spotify API, so authoritative guide is the Spotify Documentation.

[Get Current User's Playlists][https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-list-of-current-users-playlists](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recently-played)

It says that you can retrieve 1-50 elements, so that is fixed on Spotify's end. 
Now what I do not know if they only store the last 50 elements, because in that case this is not a bug.  What you could try is to move the timestamp in a way to see if actually you start to get _less_ and _less_ results. 

For me, our code appears to be fine, it even checks that you did not accidentally put both `before` and `after` in the querry, in which case you must get an error. What I would suggest is to try first if the  `before` or `after` has any effect on your results.  If you start with different before/after cut-off points and say 10 elements, you should get different results. If you get the same result all the time then this will go on the bug list.

**Comment by lucasjl** [comment]
Thank you for your time and kindness to respond. 

I did run a few tests and noticed I was not adding the last 3 digits referencing milliseconds to my searches. It did work better after that and I'm now able to get more or less elements depending on the unix timestamp I add. So I don't think there's a bug to be added to the list. 

I did discover that the API does not take more than the last 50 played songs, so if I try to use the `before` parameter to get something from last week, for example, it returns nothing because I've already listened to 50 songs this week, for example. 

I guess I'll still keep it as a learning project knowing that it won't be as cool as I imagined it could be if I had weeks or months of data from the API. Maybe I'll ask to download my whole data so I can get my complete history and then I'll work with that. If anyone else is interested, you can do that on [https://www.spotify.com/us/account/privacy/](https://www.spotify.com/us/account/privacy/) > 'Download your data'. 

Thanks again, I've been learning a lot with this package. I do appreciate all the work that has been done to create and maintain `spotifyr`.
