### ISSUE TITLE
Weird "matrix is not a sub-multiple or multiple of the number of rows" error

### ISSUE THREAD

**Issue by eoppe1022** [charlie86/spotifyr#18]
Hey Charlie, really sorry if I'm overwhelming you with the issues here.

For some reason, some artists, like Freddie Gibbs, return an error when trying to get their audio data

``` r
get_artist_audio_features("Freddie Gibbs")
#> Warning in matrix(., nrow = length(content), byrow = T): data length [1512]
#> is not a sub-multiple or multiple of the number of rows [100]
#> Error in names(audio_features_df) <- names(content[[1]]): 'names' attribute [18] must be the same length as the vector [16]
```

Strangely though, `get_artist_albums("Freddie Gibbs")` works.

**Comment by charlie86** [comment]
@eoppe1022 not at all! keep em coming - it's really helpful to have these issues pointed out, and I really appreciate it.

It looks like was due to the API rate limiting, so requests would fail when pulling a bunch of data at once. I just pushed a fix to retry all of the api calls when they return errors, and this example is working for me now on the latest master branch

**Comment by Chris-Vitalis** [comment]
Hey Charlie, I'm having a similar issue but with the get_user_audio_features. Here's what the error looks like. 
` playlist_name_A <- get_user_audio_features("classykid")
#>Error in names(audio_features_df) <- names(content[[1]]) : 
#'names' attribute [18] must be the same length as the vector [15]
#In addition: Warning message:
#In matrix(., nrow = length(content), byrow = T) :
#data length [1458] is not a sub-multiple or multiple of the number of rows [100]`
Thank you!
