### ISSUE TITLE
How to get a track's ID?

### ISSUE THREAD

**Issue by AtomicNess123** [charlie86/spotifyr#180]
I couldn't find a function for this. Many functions ask for the ID of tracks.

**Comment by 18kimn** [comment]
I believe the intended way is to use the `/search` endpoint, which will have a column for the song ID in the response

**Comment by antaldaniel** [comment]
I was thinking to add this to the documentation of the function, but it seems so obvious to me, if somebody reads the README of the package will find the search_spotify() function.

**Comment by AtomicNess123** [comment]
I'm not a programmer, and couldn't understand how to do this. What is the /search endpoint? How to extract the ID of the tracks with Spotifyr?:)

**Comment by 18kimn** [comment]
You can use the `search_spotify` function in this package to search for albums, artists, playlists, or tracks. To get the ID for the song "Good Days" (by Sza):

```
search_results <- search_spotify("Good Days", type = "track")
View(search_results)
```

If you are able to, you should visually inspect the search result. I see that the first item is the song by Sza, which makes sense since it is quite popular.

To see the actual song ID, I can copy it from the preview shown by `View(search_results)` or get it with:

```
search_results$id[1]
# [1] "3YJJjQPAbDT7mGpX3WtQ9A"
```

**Comment by antaldaniel** [comment]
Every song (album, artist) URL endpoint has an ID, for a song, for example, [https://open.spotify.com/track/6UszqmX3UxaiKbNArwwZ0q](https://open.spotify.com/track/6UszqmX3UxaiKbNArwwZ0q)   after the track part. 

However, you won't be able to use this package if you do not read at least the README, and generally, some level of familiarity with Spotify and the web technologies is required to use reproducible retrieval.  The github issues are for programming bugs and documentation improvements, not general programming help.

**Comment by 18kimn** [comment]
@AtomicNess123 if you have further trouble I'm happy to help out, you could message me on twitter via my handle @/nathanckim or email me at nathan.kim[at]yale.edu .

**Comment by AtomicNess123** [comment]
Thanks, people, I will try with search_spotify and see how it goes.

**Comment by AtomicNess123** [comment]
I wanted to actually get the audio features of (1) recently played tracks (using `get_my_recently_played`) and (2) favourite tracks (using `get_my_top_artists_or_tracks`).

I suppose I can use `get_track_audio_features(ids, authorization = get_spotify_access_token())`

And I suppose I can't feed that function with the output of the other two.
First I would need to find the ID of each track and then feed it as a loop to the `get_track_audio_features` funcion.
Would this be correct?

**Comment by 18kimn** [comment]
No, you can definitely feed the `get_track_audio_features` function with the output of `get_my_recently_played` and `get_my_top_artists_or_tracks`. Both of those latter two functions return a table with a column called `track.id`, so that's what you'd want to pass into `get_track_audio_features`.

For example, the following line of code worked for me:

```
get_track_audio_features(get_my_recently_played()$track.id)
```

For further questions please ask on the StackOverflow forums or contact me via the info above, so we don't crowd this repository's Github issues or bother the maintainers. :)
