### ISSUE TITLE
Is this package working for 4.2.2 version of R?

### ISSUE THREAD

**Issue by CostanzaG** [charlie86/spotifyr#190]

**Comment by RaymondBalise** [comment]
Yesterday it was not available on CRAN and the GitHub release would not build.  The authors (kindly) put in a patch.  

This morning I was able to successfully run: devtools::install_github('charlie86/spotifyr').

**Comment by antaldaniel** [comment]
If you read the issues, this is because you can read on CRAN, too: a dependency was archived before being removed from this package. The current development version does not refer to the genius dependency.  It will take 1-2 days until spotifyR will be back on CRAN again.  But you can safely use the development version.

**Comment by antaldaniel** [comment]
Version 2.2.4 is now on CRAN.

**Comment by RaymondBalise** [comment]
Awesome!
