### ISSUE TITLE
ERROR: "Cannot find albums for [artist X] on spotify"

### ISSUE THREAD

**Issue by josephquinn** [charlie86/spotifyr#9]
Hi @charlie86,

The new version of 'get_artist_audio_features()' is exhibiting an odd error. Consider an example that requests data for "The Weeknd." When I simply call

`get_artist_audio_features("The Weeknd")`

I get this error:

```
Error in get_artist_audio_features("The Weeknd") : 
  Cannot find any albums for "The Weeknd" on Spotify
```

I then specify who the artist is manually with the newly added function, but get this error:

```
Error in get_artist_audio_features("The Weeknd", return_closest_artist = F) : 
  Cannot find any albums for "The Weeknd" on Spotify
```

The problem here is that The Weeknd *definitely* has albums on spotify. I thought perhaps I was over-requesting, but if I do the same thing for, say, "Taylor Swift," I immediately get the requested data.

Any thoughts? It's especially bizarre because I ran identical syntax last night and it worked.

**Comment by josephquinn** [comment]
The good news is that the error appears to consistently occur for certain artists. Restarting R, rerunning my for loop, re-using get_artist_audio_features() yields the same problem for the same artists each time:

```
Error in get_artist_audio_features(topartists[i]) : 
  Cannot find any albums for "Justin Bieber" on Spotify

Error in get_artist_audio_features(topartists[i]) : 
  Cannot find any albums for "Ariana Grande" on Spotify
```

Perhaps the function has cultivated musical tastes and knows when to say 'no'!

**Comment by charlie86** [comment]
@josephquinn hahahaha I wish that were the case!

Actually it looks like you're not far off. I've found two contributing factors to the bug, and pop musicians are especially susceptible to both. 

1. There's a 50 album limit set by spotify's Search endpoint, so it's not actually finding all of their albums. This can be fixed with a loop that batches by 50.

2. The get_albums() function has a hard coded condition that the first artist listed by Spotify for the album be the same artist that was searched for, so all these collaboration albums and compilations are often skipped. I'll go back and add this as an optional flag.

Thanks a bunch for pointing this out! I'm not sure when I'll get to this, but if you want to take a stab at a PR I'd be happy to review and merge.

**Comment by josephquinn** [comment]
Awesome - I have a few deadlines tomorrow but I'll give it a shot on Thursday if it's still pending

**Comment by charlie86** [comment]
@josephquinn i just pushed a fix for issue #1, which solved the cases you pointed out. I'll leave this issue open though, because i still need to deal with issue #2

**Comment by josephquinn** [comment]
Thanks a lot for this! Sorry I fell off - I'll test it later today

**Comment by charlie86** [comment]
Just added an optional flag (that defaults to TRUE) for filtering single/collab albums
