### ISSUE TITLE
get_playlist_audio_features() doesn't work

### ISSUE THREAD

**Issue by TasoulasTheofanis** [charlie86/spotifyr#97]
Hello, i'm trying to use the get_playlist_audio_features function, but it R says:
 could not find function "get_playlist_audio_features"

I'm using the example shown on the documentary: https://cloud.r-project.org/web/packages/spotifyr/spotifyr.pdf

> playlist_username <- 'spotify'
> playlist_uris <- c('37i9dQZF1E9T1oFsQFg98K', '37i9dQZF1CyQNOI21QVf3p')
> playlist_audio_features <- get_playlist_audio_features(playlist_username, playlist_uris)

Any ideas what's going on? Thanks.

**Comment by charlie86** [comment]
@TasoulasTheofanis 

Have you loaded the package? 
`library(spotifyr)`

It should be there.

**Comment by TasoulasTheofanis** [comment]
Of course i did.  My R version is 3.5.0  Other functions such as get_artist_audio_features() work fine.

**Comment by charlie86** [comment]
@TasoulasTheofanis Have you tried reinstalling? I can't reproduce your issue

**Comment by jenren** [comment]
Not sure if I'm running into the exact same issue as @TasoulasTheofanis but I'm also having issues using this method. For me, I think it might be because I don't have a username associated with my Spotify account and I believe I'm unable to set one up? (I created it ages ago linked to Facebook). 

When I try to pass my user id instead, it returns a 404. Any idea what I might be doing wrong?

``
get_playlist_audio_features(username = "#######", playlist_uris = c("MYPLAYLISTURI"))
``

Result:

> Error in get_playlist(playlist_uri) : Not Found (HTTP 404).

**Comment by jenren** [comment]
Oops, resolved my issue which was because I defined my playlist uri as follows:

``
playlist_uri <-
  get_my_playlists(authorization = access_token) %>% 
  filter(name == "chilled out") %>% 
  select(uri) %>% 
  pull()
``

which returns a string of format `"spotify:playlist:MYPLAYLISTURI"` when `get_playlist_audio_features(...)` expects just `"MYPLAYLISTURI"`. 

I think my confusion resulted from `get_playlist_tracks(playlist_id)` and `get_playlist_audio_features(username, playlist_uris)` appearing similar but having differently named args for the same information.

**Comment by charlie86** [comment]
@jenren Ya that is a fair point. I'll add it to my list of things to fix. Thanks!
